import {IDictionaryItem, IUser} from "../../types.ts";
import {easyDictionary} from "./easy-dictionary.ts";

export const defaultUserDict:  IDictionaryItem[] = [
    {
        id: 'u0',
        word: 'apple',
        transcription: 'ˈæpl',
        translate: 'яблоко',
        phrase: '',
        noun: 'яблоко',
        verb: '',
        adjective: '',
        adverb: '',
        conjunction: '',
        interjection: '',
        numeral: '',
        part: '',
        preposition: '',
        pronoun: '',
        learning: 0,
        popular: 23,
    },
    {
        id: 'u1',
        word: 'benedict',
        transcription: 'benedikt',
        translate: 'бенедикт',
        phrase: '',
        noun: 'игра в слова',
        verb: 'играть в слова',
        adjective: '',
        adverb: '',
        conjunction: '',
        interjection: '',
        numeral: '',
        part: '',
        preposition: '',
        pronoun: '',
        learning: 5,
        popular: 1,
    },
    {
        id: 'u2',
        word: 'before',
        transcription: 'bɪˈfɔːr',
        translate: 'раньше',
        phrase: 'before noon',
        noun: '',
        verb: '',
        adjective: '',
        adverb: 'раньше',
        conjunction: 'прежде',
        interjection: '',
        numeral: '',
        part: '',
        preposition: 'перед',
        pronoun: '',
        learning: 5,
        popular: 523,
    },
    {
        id: 'u3',
        word: 'it',
        transcription: 'ɪt',
        translate: 'это',
        phrase: 'it is a book',
        noun: '',
        verb: '',
        adjective: '',
        adverb: '',
        conjunction: '',
        interjection: '',
        numeral: '',
        part: '',
        preposition: '',
        pronoun: '',
        learning: 0,
        popular: 45,
    },
    {
        id: 'u4',
        word: 'why',
        transcription: 'waɪ',
        translate: 'почему',
        phrase: 'why are you here?',
        noun: '',
        verb: '',
        adjective: '',
        adverb: 'почему',
        conjunction: 'почему',
        interjection: '',
        numeral: '',
        part: '',
        preposition: '',
        pronoun: '',
        learning: 0,
        popular: 521,
    },
]
export const defaultUser: IUser = {
    objectId: '0',
    username: 'Guest',
    isBG:false,
    isEasyForm: true,
    isDarkTheme: true,
    isUserDictionary: false,
    userDict: easyDictionary,
    colorUI: 'gray',
    userRecord: 0,
    language: 'en',
}