import {IDictionaryItem, IUser} from "../../types.ts";

export const defaultUserDict:  IDictionaryItem[] = [
    {
        id: 'u0',
        word: 'apple',
        transcription: 'ˈæpl',
        descrip: '',
        phrase: '',
        noun: 'яблоко',
        verb: '',
        adjective: '',
        adverb: '',
        conjunction: '',
        interjection: '',
        numeral: '',
        part: '',
        preposition: '',
        pronoun: '',
        learning: 0,
        popular: 23,
    },
    {
        id: 'u1',
        word: 'benedict',
        transcription: 'benedikt',
        descrip: '',
        phrase: '',
        noun: 'игра в слова',
        verb: 'играть в слова',
        adjective: '',
        adverb: '',
        conjunction: '',
        interjection: '',
        numeral: '',
        part: '',
        preposition: '',
        pronoun: '',
        learning: 5,
        popular: 1,
    },
    {
        id: 'u2',
        word: 'before',
        transcription: 'bɪˈfɔːr',
        descrip: 'used to indicate the time or event that precedes or comes earlier',
        phrase: 'before noon',
        noun: '',
        verb: '',
        adjective: '',
        adverb: 'раньше',
        conjunction: 'прежде',
        interjection: '',
        numeral: '',
        part: '',
        preposition: 'перед',
        pronoun: '',
        learning: 5,
        popular: 523,
    },
    {
        id: 'u3',
        word: 'it',
        transcription: 'ɪt',
        descrip: 'used to refer to a thing, animal, or idea that has already been mentioned or is known about',
        phrase: 'it is a book',
        noun: '',
        verb: '',
        adjective: '',
        adverb: '',
        conjunction: '',
        interjection: '',
        numeral: '',
        part: '',
        preposition: '',
        pronoun: '',
        learning: 0,
        popular: 45,
    },
    {
        id: 'u4',
        word: 'why',
        transcription: 'waɪ',
        descrip: 'used to ask or talk about the reason for something',
        phrase: 'why are you here?',
        noun: '',
        verb: '',
        adjective: '',
        adverb: 'почему',
        conjunction: 'почему',
        interjection: '',
        numeral: '',
        part: '',
        preposition: '',
        pronoun: '',
        learning: 0,
        popular: 521,
    },
]
export const defaultUser: IUser = {
    objectId: '0',
    username: 'Guest',
    isBG:false,
    isDarkTheme: true,
    isUserDictionary: false,
    userDict: defaultUserDict,
}